Repository dimforge/nalgebra, pull requests merged in 2019-02, with the labels that each got.

#499 Add features required by rusty-machine.
  nalgebra-glm/src/gtc/integer.rs
  nalgebra-glm/src/gtc/packing.rs
  nalgebra-glm/tests/lib.rs
  src/base/alias_slice.rs
  src/base/blas.rs
  src/base/construction.rs
  src/base/edition.rs
  src/base/indexing.rs
  src/base/iter.rs
  src/base/matrix.rs
  src/base/mod.rs
  src/base/norm.rs
  src/base/statistics.rs
  src/geometry/isometry.rs
  src/geometry/isometry_construction.rs
  src/geometry/orthographic.rs
  src/geometry/quaternion.rs
  src/geometry/quaternion_construction.rs
  src/geometry/rotation.rs
  src/geometry/rotation_specialization.rs
  src/geometry/similarity_construction.rs
  src/geometry/transform.rs
  src/geometry/unit_complex.rs
  src/geometry/unit_complex_construction.rs
  tests/core/edition.rs
  tests/core/matrix.rs
  tests/linalg/full_piv_lu.rs
Labels: breaking change, enhancement

#385 Remove the Deref implementation for MatrixVec
  CHANGELOG.md
  src/base/construction.rs
  src/base/vec_storage.rs
Labels: breaking change

#480 Add as_ptr and as_mut_ptr methods
  src/base/matrix.rs
Labels: P-medium, enhancement

#552 `iter::Sum` for `DMatrix`
  src/base/ops.rs
Labels: enhancement
