Repository dimforge/nalgebra, pull requests merged in 2020-01, with the labels that each got.

#686 Fix slerp for regular vectors.
  src/base/matrix.rs
  src/geometry/quaternion.rs
Labels: breaking change

#691 Merge pull request #691 from alexbool/lapack-src-0.4
  ci/build.sh
  ci/test.sh
  nalgebra-lapack/Cargo.toml
Labels: P-medium, breaking change

#692 Fix Matrix PartialEq bug and add some generalization
  src/base/dimension.rs
  src/base/matrix.rs
  tests/core/matrix.rs
  tests/core/serde.rs
Labels: P-medium, breaking change, enhancement
